import type { ThemeId } from "./types";

export const THEME_POOLS: Record<ThemeId, string[]> = {
  naturaleza: [
    "BOSQUE", "MONTAÑA", "RIO", "LAGO", "FLOR", "ARBOL", "CIELO", "MAR", "PLAYA",
    "VALLE", "CASCADA", "SENDERO", "JARDIN", "FUENTE", "LAGUNA", "PRADO", "CUEVA",
    "GLACIAR", "VOLCAN", "ISLA", "DESIERTO", "SELVA", "OCEANO", "ESTRELLA", "LUNA",
    "SOL", "NUBE", "VIENTO", "LLUVIA", "ARCOIRIS",
  ],
  autos: [
    "MOTOR", "RUEDA", "VOLANTE", "FRENO", "MARCHA", "COCHE", "CAMION", "MOTO",
    "AUTO", "TURBO", "CHASIS", "FARO", "NEUMATICO", "EMBRAGUE", "RADIADOR",
    "ESCAPE", "CILINDRO", "PISTON", "BATERIA", "CARRETERA", "GARAJE", "TALLER",
    "VELOCIDAD", "CINTURON", "AIRBAG", "TABLERO", "PALANCA", "ASIENTO", "PUERTA",
    "CAPO",
  ],
  valores: [
    "AMOR", "PAZ", "RESPETO", "HONESTIDAD", "LEALTAD", "SOLIDARIDAD", "PERDON",
    "GRATITUD", "HUMILDAD", "PACIENCIA", "TOLERANCIA", "RESPONSABILIDAD", "JUSTICIA",
    "LIBERTAD", "IGUALDAD", "VERDAD", "BONDAD", "SABIDURIA", "VALENTIA", "PRUDENCIA",
    "COMPRENSION", "EMPATIA", "CONFIANZA", "ESPERANZA", "ALEGRIA", "SINCERIDAD",
    "NOBLEZA", "FORALEZA", "CARIDAD", "DIGNIDAD",
  ],
  animales: [
    "PERRO", "GATO", "ELEFANTE", "LEON", "TIGRE", "OSO", "LOBO", "ZORRO", "CONEJO",
    "CABALLO", "VACA", "OVEJA", "CERDO", "GALLINA", "GORRION", "AGUILA", "HALCON",
    "DELFIN", "BALLENA", "TIBURON", "SERPIENTE", "COCODRILO", "RANA", "SAPO",
    "MARIPOSA", "ABEJA", "HORMIGA", "ARAÑA", "CARACOL", "TORO",
  ],
  colores: [
    "ROJO", "AZUL", "VERDE", "AMARILLO", "NEGRO", "BLANCO", "GRIS", "MARRON",
    "NARANJA", "VIOLETA", "ROSADO", "DORADO", "PLATEADO", "CELESTE", "BEIGE",
    "TURQUESA", "ESMERALDA", "RUBI", "LILA", "MAGENTA", "CIAN", "MOSTAZA",
    "OLIVA", "BURDEOS", "FUCSIA", "LAVANDA", "COBALTO", "CAOBA", "EBANO", "MARFIL",
  ],
  comida: [
    "MANZANA", "BANANA", "NARANJA", "FRESA", "UVA", "SANDIA", "MELON", "PERA",
    "DURAZNO", "CEREZA", "PAN", "LECHE", "QUESO", "HUEVO", "ARROZ", "PASTA",
    "CARNE", "POLLO", "PESCADO", "TOMATE", "LECHUGA", "CEBOLLA", "ZANAHORIA",
    "PAPA", "CHOCOLATE", "HELADO", "GALLETA", "TARTA", "YOGURT", "MIEL",
  ],
  deportes: [
    "FUTBOL", "BASQUET", "TENIS", "NATACION", "ATLETISMO", "CICLISMO", "VOLEIBOL",
    "BEISBOL", "RUGBY", "GOLF", "BOXEO", "KARATE", "JUDO", "ESGRIMA", "HOCKEY",
    "ESQUI", "SURF", "REM0", "CANOTAJE", "TIRO", "GIMNASIA", "LUCHA", "PESAS",
    "PATINAJE", "SALTO", "MARATON", "TRIATLON", "PADDLE", "SQUASH", "BADMINTON",
  ],
  profesiones: [
    "MEDICO", "INGENIERO", "ABOGADO", "MAESTRO", "ARQUITECTO", "BOMBERO", "POLICIA",
    "ENFERMERO", "VETERINARIO", "PERIODISTA", "JUEZ", "FARMACEUTICO", "DENTISTA",
    "PSICOLOGO", "ASTRONAUTA", "PILOTO", "MARINO", "CHEF", "CARPINTERO", "ELECTRICISTA",
    "PLOMERO", "PINTOR", "ESCRITOR", "ACTOR", "CANTANTE", "BAILARIN", "FOTOGRAFO",
    "DISENADOR", "PROGRAMADOR", "CONTADOR",
  ],
  musica: [
    "GUITARRA", "PIANO", "BATERIA", "VIOLIN", "FLAUTA", "TROMPETA", "SAXOFON",
    "BAJO", "ARPA", "ACORDEON", "MELODIA", "RITMO", "ARMONIA", "COMPAS", "NOTA",
    "CORO", "SOLISTA", "ORQUESTA", "BANDA", "CONCIERTO", "CANTO", "OPERA",
    "JAZZ", "ROCK", "CLASICA", "BLUES", "SAMBA", "TANGO", "SALSA", "REGGAE",
  ],
  viajes: [
    "AVION", "TREN", "BARCO", "AUTOBUS", "MALETA", "PASAJE", "VUELO", "HOTEL",
    "MAPA", "BRUJULA", "CAMARA", "MOCHILA", "PLAYA", "MONTAÑA", "CIUDAD",
    "PAIS", "FRONTERA", "IDIOMA", "CULTURA", "AVENTURA", "DESTINO", "VIAJERO",
    "TURISTA", "GUIA", "EXCURSION", "CRUCERO", "MOTEL", "ALBERGUE", "CARRETERA",
    "AEROPUERTO",
  ],
  casa: [
    "SALA", "COCINA", "BAÑO", "RECAMARA", "COMEDOR", "PATIO", "JARDIN", "GARAJE",
    "VENTANA", "PUERTA", "PISO", "TECHO", "PARED", "MUEBLE", "SILLA", "MESA",
    "CAMA", "ARMARIO", "LAMPARA", "ESPEJO", "CORTINA", "COJIN", "ALFOMBRA",
    "CUADRO", "FLORERO", "RELOJ", "TELEFONO", "LAVADOR", "ESTUFA", "REFRIGERADOR",
  ],
  ropa: [
    "CAMISA", "PANTALON", "VESTIDO", "FALDA", "CHAQUETA", "ABRIGO", "SUETER",
    "ZAPATOS", "BOTAS", "SANDALIAS", "TENIS", "MEDIAS", "CALCETINES", "CINTURON",
    "CORBATA", "BUFANDA", "GORRA", "SOMBRERO", "GUANTES", "GAFAS", "BOLSILLO",
    "BOTON", "CIERRE", "CUELLO", "MANGA", "CAMINETA", "BERMUDAS", "BLUSA",
    "CHALECO", "IMPERMEABLE",
  ],
};
