export interface CrosswordWordEntry {
  word: string;
  clue: string;
}

export const CROSSWORD_BANK: Record<string, CrosswordWordEntry[]> = {
  general: [
    { word: "CASA", clue: "Vivienda de las personas" },
    { word: "PERRO", clue: "Mejor amigo del hombre" },
    { word: "GATO", clue: "Animal que caza ratones" },
    { word: "SOL", clue: "Estrella del sistema solar" },
    { word: "LUNA", clue: "Satelite natural de la Tierra" },
    { word: "MAR", clue: "Gran masa de agua salada" },
    { word: "CIELO", clue: "Lo que vemos sobre nosotros" },
    { word: "FLOR", clue: "Parte colorida de las plantas" },
    { word: "ARBOL", clue: "Planta grande con hojas y raices" },
    { word: "FUEGO", clue: "Produce calor y luz" },
    { word: "AGUA", clue: "Liquido vital e incoloro" },
    { word: "TIERRA", clue: "Planeta donde vivimos" },
    { word: "NUBE", clue: "Vapor de agua en el cielo" },
    { word: "PLAYA", clue: "Lugar con arena y mar" },
    { word: "MONTE", clue: "Elevacion natural del terreno" },
    { word: "LIBRO", clue: "Conjunto de hojas escritas" },
    { word: "LAPIZ", clue: "Instrumento para escribir" },
    { word: "VENTANA", clue: "Abertura con vidrio en la pared" },
    { word: "PUERTA", clue: "Entrada a un lugar" },
    { word: "MESA", clue: "Mueble con superficie plana" },
    { word: "SILLA", clue: "Asiento con respaldo" },
    { word: "AMOR", clue: "Sentimiento de afecto profundo" },
    { word: "PAZ", clue: "Estado de tranquilidad y armonia" },
    { word: "TIEMPO", clue: "Duracion de las cosas" },
    { word: "RELOJ", clue: "Sirve para medir el tiempo" },
    { word: "CAMINO", clue: "Via para transitar" },
    { word: "CIUDAD", clue: "Lugar con muchos habitantes" },
    { word: "MUNDO", clue: "Totalidad de lo existente" },
    { word: "VIDA", clue: "Estado de actividad de los seres" },
    { word: "LUZ", clue: "Energia que ilumina" },
    { word: "SOMBRA", clue: "Ausencia de luz" },
    { word: "ALMA", clue: "Parte espiritual del ser" },
    { word: "CUERPO", clue: "Parte material de una persona" },
    { word: "META", clue: "Objetivo a alcanzar" },
    { word: "FUERZA", clue: "Capacidad para realizar trabajo" },
  ],
  naturaleza: [
    { word: "BOSQUE", clue: "Gran extension de arboles" },
    { word: "SELVA", clue: "Vegetacion tropical densa" },
    { word: "MONTANA", clue: "Gran elevacion natural" },
    { word: "VALLE", clue: "Terreno entre montanas" },
    { word: "RIO", clue: "Corriente de agua natural" },
    { word: "LAGO", clue: "Masa de agua rodeada de tierra" },
    { word: "OCEANO", clue: "Inmensa masa de agua salada" },
    { word: "DESIERTO", clue: "Region con poca vegetacion" },
    { word: "VOLCAN", clue: "Montana que expulsa lava" },
    { word: "CASCADA", clue: "Agua que cae desde una altura" },
    { word: "ISLA", clue: "Tierra rodeada de agua" },
    { word: "CUEVA", clue: "Abertura natural subterranea" },
    { word: "PINO", clue: "Arbol de hojas en forma de aguja" },
    { word: "ROBLE", clue: "Arbol de madera muy resistente" },
    { word: "PALMERA", clue: "Arbol tipico de playas tropicales" },
    { word: "GIRASOL", clue: "Planta que sigue al sol" },
    { word: "LLUVIA", clue: "Agua que cae de las nubes" },
    { word: "NIEVE", clue: "Agua congelada que cae del cielo" },
    { word: "TORMENTA", clue: "Fenomeno con lluvia y truenos" },
    { word: "ARCOIRIS", clue: "Arco de colores en el cielo" },
    { word: "AMANECER", clue: "Primeras horas del dia" },
    { word: "ATARDECER", clue: "Ultimas horas del dia" },
    { word: "ARENA", clue: "Granos finos en la playa" },
    { word: "PIEDRA", clue: "Material solido y duro" },
    { word: "MONTE", clue: "Elevacion de terreno" },
    { word: "LAGUNA", clue: "Lago pequeno y poco profundo" },
    { word: "COSTA", clue: "Limite entre tierra y mar" },
    { word: "MAREA", clue: "Movimiento del nivel del mar" },
    { word: "CLIMA", clue: "Condiciones atmosfericas habituales" },
    { word: "FLORA", clue: "Conjunto de plantas de una region" },
    { word: "FAUNA", clue: "Conjunto de animales de una region" },
    { word: "ECOLOGIA", clue: "Estudio del medio ambiente" },
    { word: "PAISAJE", clue: "Extension de terreno que se ve" },
    { word: "PRIMAVERA", clue: "Estacion de las flores" },
    { word: "VERANO", clue: "Estacion mas calida del ano" },
    { word: "INVIERNO", clue: "Estacion mas fria del ano" },
  ],
  animales: [
    { word: "ELEFANTE", clue: "Animal terrestre mas grande" },
    { word: "LEON", clue: "Rey de la selva" },
    { word: "TIGRE", clue: "Felino de piel rayada" },
    { word: "OSO", clue: "Mamifero grande y peludo" },
    { word: "LOBO", clue: "Animal que aulla a la luna" },
    { word: "ZORRO", clue: "Animal conocido por su astucia" },
    { word: "CONEJO", clue: "Animal de orejas largas" },
    { word: "CABALLO", clue: "Animal que se monta" },
    { word: "VACA", clue: "Animal que produce leche" },
    { word: "GALLINA", clue: "Ave que pone huevos" },
    { word: "AGUILA", clue: "Ave de presa de gran envergadura" },
    { word: "DELFIN", clue: "Mamifero marino inteligente" },
    { word: "BALLENA", clue: "Mamifero marino mas grande" },
    { word: "TIBURON", clue: "Pez grande y peligroso" },
    { word: "SERPIENTE", clue: "Reptil sin patas" },
    { word: "RANA", clue: "Anfibio que salta y croa" },
    { word: "MARIPOSA", clue: "Insecto con alas coloridas" },
    { word: "ABEJA", clue: "Insecto que produce miel" },
    { word: "HORMIGA", clue: "Insecto muy trabajador" },
    { word: "TORO", clue: "Mamifero bovino macho" },
    { word: "PATO", clue: "Ave que nada en el agua" },
    { word: "LORO", clue: "Ave que puede imitar la voz" },
    { word: "PINGUINO", clue: "Ave que no vuela, vive en el polo" },
    { word: "JIRAFA", clue: "Animal de cuello muy largo" },
    { word: "CEBRA", clue: "Animal de rayas blancas y negras" },
    { word: "CANGURO", clue: "Mamifero que salta y tiene bolsa" },
    { word: "KOALA", clue: "Mamifero australiano que come hojas" },
    { word: "PANDA", clue: "Oso blanco y negro de China" },
    { word: "ARDILLA", clue: "Roquedor de cola esponjosa" },
    { word: "TORTUGA", clue: "Reptil con caparazon duro" },
    { word: "IGUANA", clue: "Lagarto grande de America" },
    { word: "PULPO", clue: "Animal marino con ocho brazos" },
    { word: "ESTRELLA", clue: "Animal marino con forma de estrella" },
  ],
  comida: [
    { word: "MANZANA", clue: "Fruta roja o verde del manzano" },
    { word: "BANANA", clue: "Fruta amarilla y alargada" },
    { word: "NARANJA", clue: "Fruta citrica de color naranja" },
    { word: "FRESA", clue: "Fruta roja pequena y dulce" },
    { word: "UVA", clue: "Fruta que se usa para hacer vino" },
    { word: "SANDIA", clue: "Fruta grande verde por fuera y roja por dentro" },
    { word: "MELON", clue: "Fruta grande y dulce con cascara amarilla" },
    { word: "PERA", clue: "Fruta de forma alargada y dulce" },
    { word: "PAN", clue: "Alimento hecho con harina y horno" },
    { word: "LECHE", clue: "Bebida blanca de origen animal" },
    { word: "QUESO", clue: "Alimento solido hecho de leche" },
    { word: "HUEVO", clue: "Alimento de forma ovalada" },
    { word: "ARROZ", clue: "Cereal blanco muy consumido" },
    { word: "PASTA", clue: "Comida italiana de harina" },
    { word: "CARNE", clue: "Alimento de origen animal" },
    { word: "POLLO", clue: "Ave que se consume como alimento" },
    { word: "PESCADO", clue: "Alimento que viene del mar" },
    { word: "TOMATE", clue: "Fruta roja usada en ensaladas" },
    { word: "LECHUGA", clue: "Verdura de hojas verdes" },
    { word: "CEBOLLA", clue: "Bulbo comestible que hace llorar" },
    { word: "CHOCOLATE", clue: "Dulce hecho de cacao" },
    { word: "HELADO", clue: "Postre frio y cremoso" },
    { word: "GALLETA", clue: "Masa horneada pequena y dulce" },
    { word: "MIEL", clue: "Sustancia dulce hecha por abejas" },
    { word: "SOPA", clue: "Comida liquida caliente" },
    { word: "ENSALADA", clue: "Mezcla de verduras fria" },
    { word: "LENTEJAS", clue: "Legumbre pequena y nutritiva" },
    { word: "MAIZ", clue: "Cereal amarillo en mazorca" },
    { word: "JAMON", clue: "Carne curada del cerdo" },
    { word: "CAFE", clue: "Bebida caliente amarga y energetica" },
    { word: "TE", clue: "Infusion de hojas" },
    { word: "CERVEZA", clue: "Bebida alcoholica de cebada" },
    { word: "VINO", clue: "Bebida de uvas fermentadas" },
  ],
  deportes: [
    { word: "FUTBOL", clue: "Deporte con pelota que se juega con los pies" },
    { word: "BASQUET", clue: "Deporte donde se anota en una canasta" },
    { word: "TENIS", clue: "Deporte que se juega con raqueta" },
    { word: "NATACION", clue: "Deporte que se practica en el agua" },
    { word: "CICLISMO", clue: "Deporte que se practica en bicicleta" },
    { word: "VOLEIBOL", clue: "Deporte donde se golpea un balon por encima de una red" },
    { word: "BEISBOL", clue: "Deporte con bate y pelota" },
    { word: "RUGBY", clue: "Deporte de contacto con pelota ovalada" },
    { word: "GOLF", clue: "Deporte donde se golpea una pelota con palo" },
    { word: "BOXEO", clue: "Deporte de combate con puos" },
    { word: "KARATE", clue: "Arte marcial de origen japones" },
    { word: "HOCKEY", clue: "Deporte que se juega con un palo y un disco" },
    { word: "ESQUI", clue: "Deporte que se practica en la nieve" },
    { word: "SURF", clue: "Deporte que se practica sobre las olas" },
    { word: "REMO", clue: "Deporte que se practica en bote con remos" },
    { word: "GIMNASIA", clue: "Deporte que requiere fuerza y flexibilidad" },
    { word: "LUCHA", clue: "Deporte de combate cuerpo a cuerpo" },
    { word: "PELOTA", clue: "Objeto esferico usado en muchos deportes" },
    { word: "CANCHA", clue: "Lugar donde se practican deportes" },
    { word: "ESTADIO", clue: "Gran instalacion deportiva" },
    { word: "PISTA", clue: "Lugar para correr o practicar deportes" },
    { word: "ARBITRO", clue: "Persona que hace cumplir las reglas" },
    { word: "JUGADOR", clue: "Persona que practica un deporte" },
    { word: "ENTRENADOR", clue: "Persona que prepara a los deportistas" },
    { word: "CAMPEON", clue: "Ganador de una competencia" },
    { word: "MEDALLA", clue: "Premio que se cuelga del cuello" },
    { word: "TROFEO", clue: "Premio que se levanta con las manos" },
    { word: "MARATON", clue: "Carrera de larga distancia" },
    { word: "SALTO", clue: "Accion de elevarse del suelo" },
    { word: "VELOCIDAD", clue: "Capacidad de moverse rapido" },
    { word: "GOL", clue: "Anotacion en el futbol" },
    { word: "CANASTA", clue: "Anotacion en el basquet" },
  ],
  profesiones: [
    { word: "MEDICO", clue: "Profesional que cura enfermedades" },
    { word: "INGENIERO", clue: "Profesional que disena y construye" },
    { word: "ABOGADO", clue: "Profesional que defiende en juicios" },
    { word: "MAESTRO", clue: "Persona que ensea en la escuela" },
    { word: "ARQUITECTO", clue: "Disena edificios y casas" },
    { word: "BOMBERO", clue: "Apaga incendios y rescata personas" },
    { word: "POLICIA", clue: "Protege a la ciudadania" },
    { word: "ENFERMERO", clue: "Cuida a los pacientes en el hospital" },
    { word: "PERIODISTA", clue: "Busca y comunica noticias" },
    { word: "JUEZ", clue: "Dicta sentencias en los tribunales" },
    { word: "DENTISTA", clue: "Cuida la salud de los dientes" },
    { word: "CHEF", clue: "Cocina profesionalmente" },
    { word: "PINTOR", clue: "Crea obras de arte con colores" },
    { word: "ESCRITOR", clue: "Crea libros y textos" },
    { word: "ACTOR", clue: "Interpreta personajes en cine o teatro" },
    { word: "CANTANTE", clue: "Persona que canta profesionalmente" },
    { word: "FOTOGRAFO", clue: "Toma fotografias profesionalmente" },
    { word: "PROGRAMADOR", clue: "Crea software y aplicaciones" },
    { word: "VETERINARIO", clue: "Cuida la salud de los animales" },
    { word: "PILOTO", clue: "Conduce aviones" },
    { word: "MARINO", clue: "Trabaja en el mar" },
    { word: "CARPINTERO", clue: "Trabaja con la madera" },
    { word: "ELECTRICISTA", clue: "Trabaja con instalaciones electricas" },
    { word: "PLOMERO", clue: "Repara canerias y tuberias" },
    { word: "CIENTIFICO", clue: "Realiza investigacion y experimentos" },
    { word: "BIOLOGO", clue: "Estudia los seres vivos" },
    { word: "ASTRONOMO", clue: "Estudia los astros y el universo" },
    { word: "PROFESOR", clue: "Dicta clases en la universidad" },
    { word: "ECONOMISTA", clue: "Estudia la economia" },
    { word: "VENDEDOR", clue: "Comercializa productos" },
    { word: "SOLDADO", clue: "Defiende a la nacion" },
    { word: "JARDINERO", clue: "Cuida plantas y jardines" },
  ],
  musica: [
    { word: "GUITARRA", clue: "Instrumento de cuerdas mas popular" },
    { word: "PIANO", clue: "Instrumento de teclas blancas y negras" },
    { word: "BATERIA", clue: "Instrumento de percusion con tambores" },
    { word: "VIOLIN", clue: "Instrumento de cuerdas que se toca con arco" },
    { word: "FLAUTA", clue: "Instrumento de viento alargado" },
    { word: "TROMPETA", clue: "Instrumento de viento metalico" },
    { word: "SAXOFON", clue: "Instrumento de viento de jazz" },
    { word: "BAJO", clue: "Instrumento de cuerdas de sonido grave" },
    { word: "ARPA", clue: "Instrumento de cuerdas triangular" },
    { word: "MELODIA", clue: "Sucesion de sonidos agradable" },
    { word: "RITMO", clue: "Pulso o compas de la musica" },
    { word: "NOTA", clue: "Cada uno de los sonidos musicales" },
    { word: "CORO", clue: "Grupo de personas que cantan juntas" },
    { word: "ORQUESTA", clue: "Conjunto de musicos con diversos instrumentos" },
    { word: "BANDA", clue: "Grupo musical" },
    { word: "CONCIERTO", clue: "Espectaculo de musica en vivo" },
    { word: "CANTO", clue: "Arte de producir sonidos con la voz" },
    { word: "OPERA", clue: "Obra teatral cantada" },
    { word: "JAZZ", clue: "Genero musical de origen afroamericano" },
    { word: "ROCK", clue: "Genero musical con guitarra electrica" },
    { word: "TANGO", clue: "Baile y musica tipica de Argentina" },
    { word: "SALSA", clue: "Genero musical bailable latino" },
    { word: "CANCION", clue: "Composicion musical con letra" },
    { word: "COMPAS", clue: "Division del tiempo en la musica" },
    { word: "ORGANO", clue: "Gran instrumento de teclado con tubos" },
    { word: "SOLISTA", clue: "Musico que interpreta solo" },
    { word: "PARTITURA", clue: "Escritura musical en papel" },
    { word: "BALADA", clue: "Cancion lenta y romantica" },
    { word: "POP", clue: "Genero musical popular" },
    { word: "FOLKLORE", clue: "Musica tradicional de un pueblo" },
  ],
  viajes: [
    { word: "AVION", clue: "Medio de transporte aereo" },
    { word: "TREN", clue: "Transporte que circula sobre rieles" },
    { word: "BARCO", clue: "Transporte que navega por el agua" },
    { word: "MALETA", clue: "Equipaje para llevar cosas en un viaje" },
    { word: "VUELO", clue: "Trayecto en avion" },
    { word: "HOTEL", clue: "Lugar donde alojarse al viajar" },
    { word: "MAPA", clue: "Representacion geografica de un lugar" },
    { word: "BRUJULA", clue: "Instrumento para orientarse" },
    { word: "CAMARA", clue: "Aparato para tomar fotografias" },
    { word: "MOCHILA", clue: "Bolsa que se carga en la espalda" },
    { word: "AVENTURA", clue: "Experiencia emocionante y arriesgada" },
    { word: "DESTINO", clue: "Lugar al que se viaja" },
    { word: "VIAJERO", clue: "Persona que realiza viajes" },
    { word: "TURISTA", clue: "Persona que visita lugares por placer" },
    { word: "GUIA", clue: "Persona que muestra lugares turisticos" },
    { word: "EXCURSION", clue: "Paseo o viaje corto" },
    { word: "CRUCERO", clue: "Viaje en barco con fines turisticos" },
    { word: "PASAPORTE", clue: "Documento para viajar al extranjero" },
    { word: "RUTA", clue: "Itinerario de un viaje" },
    { word: "AEROPUERTO", clue: "Lugar donde aterrizan y despegan aviones" },
    { word: "CARRETERA", clue: "Via para automoviles" },
    { word: "FRONTERA", clue: "Limite entre dos paises" },
    { word: "IDIOMA", clue: "Lengua de un pais" },
    { word: "CULTURA", clue: "Tradiciones y costumbres de un pueblo" },
    { word: "MUSEO", clue: "Lugar donde se exponen obras de arte" },
    { word: "MONUMENTO", clue: "Obra conmemorativa en un lugar publico" },
    { word: "COSTA", clue: "Orilla del mar" },
    { word: "MONTANA", clue: "Elevacion natural visitada por turistas" },
    { word: "NATURALEZA", clue: "Entorno natural libre de urbanizacion" },
    { word: "MOCHILERO", clue: "Viajero que recorre con mochila" },
    { word: "RECUERDO", clue: "Objeto que se trae de un viaje" },
    { word: "FESTIVAL", clue: "Evento cultural o musical" },
  ],
  casa: [
    { word: "SALA", clue: "Habitacion principal de la casa" },
    { word: "COCINA", clue: "Lugar donde se prepara la comida" },
    { word: "BANO", clue: "Habitacion con inodoro y ducha" },
    { word: "COMEDOR", clue: "Lugar donde se come" },
    { word: "PATIO", clue: "Espacio exterior de la casa" },
    { word: "JARDIN", clue: "Terreno con plantas y flores" },
    { word: "GARAJE", clue: "Lugar para guardar el auto" },
    { word: "PISO", clue: "Superficie por donde se camina" },
    { word: "TECHO", clue: "Parte superior de una edificacion" },
    { word: "PARED", clue: "Division vertical de una habitacion" },
    { word: "MUEBLE", clue: "Objeto que sirve para comodidad del hogar" },
    { word: "CAMA", clue: "Mueble para dormir" },
    { word: "ARMARIO", clue: "Mueble para guardar ropa" },
    { word: "LAMPARA", clue: "Objeto que da luz" },
    { word: "ESPEJO", clue: "Superficie que refleja la imagen" },
    { word: "CORTINA", clue: "Tela que cubre las ventanas" },
    { word: "ALFOMBRA", clue: "Tapete que cubre parte del piso" },
    { word: "RELOJ", clue: "Aparato que marca la hora" },
    { word: "ESTUFA", clue: "Aparato para calentar el ambiente" },
    { word: "HORNO", clue: "Electrodomestico para cocinar" },
    { word: "SOFA", clue: "Asiento grande y acolchado" },
    { word: "DUCHA", clue: "Lugar donde se toma el bano de pie" },
    { word: "ESCALERA", clue: "Peldanos para subir o bajar" },
    { word: "PASILLO", clue: "Corredor dentro de la casa" },
    { word: "TERRAZA", clue: "Espacio al aire libre en un edificio" },
    { word: "VENTANA", clue: "Abertura con vidrio en la pared" },
    { word: "LLAVE", clue: "Instrumento para abrir cerraduras" },
    { word: "CERRADURA", clue: "Mecanismo para asegurar una puerta" },
    { word: "CALEFACCION", clue: "Sistema para calentar la casa" },
    { word: "SOTANO", clue: "Planta subterranea de la casa" },
  ],
  ropa: [
    { word: "CAMISA", clue: "Prenda con botones en la parte frontal" },
    { word: "PANTALON", clue: "Prenda que cubre las piernas" },
    { word: "VESTIDO", clue: "Prenda femenina de una sola pieza" },
    { word: "FALDA", clue: "Prenda femenina que cuelga de la cintura" },
    { word: "CHAQUETA", clue: "Prenda con mangas que se usa sobre la ropa" },
    { word: "ABRIGO", clue: "Prenda gruesa para protegerse del frio" },
    { word: "SUETER", clue: "Prenda de punto para la parte superior" },
    { word: "ZAPATOS", clue: "Calzado que cubre el pie" },
    { word: "BOTAS", clue: "Calzado que cubre hasta la pierna" },
    { word: "SANDALIAS", clue: "Calzado abierto y ligero" },
    { word: "CINTURON", clue: "Accesorio que se ajusta a la cintura" },
    { word: "CORBATA", clue: "Accesorio que se usa en el cuello" },
    { word: "BUFANDA", clue: "Prenda que se usa en el cuello" },
    { word: "SOMBRERO", clue: "Prenda que cubre la cabeza" },
    { word: "GUANTES", clue: "Prenda que cubre las manos" },
    { word: "GAFAS", clue: "Accesorio para proteger o mejorar la vision" },
    { word: "BOTON", clue: "Pieza para abrochar la ropa" },
    { word: "MODA", clue: "Tendencia en el vestir" },
    { word: "TELA", clue: "Material con que se hace la ropa" },
    { word: "LANA", clue: "Fibra textil de origen animal" },
    { word: "ALGODON", clue: "Fibra textil vegetal" },
    { word: "SEDA", clue: "Fibra textil fina y suave" },
    { word: "TALLE", clue: "Medida de la ropa" },
    { word: "JEAN", clue: "Pantalon de tela vaquera" },
    { word: "BOLSILLO", clue: "Compartimento en la ropa" },
    { word: "MANGA", clue: "Parte de la prenda que cubre el brazo" },
    { word: "CUELLO", clue: "Parte de la prenda alrededor del cuello" },
  ],
  colores: [
    { word: "ROJO", clue: "Color como la sangre" },
    { word: "AZUL", clue: "Color del cielo" },
    { word: "VERDE", clue: "Color de la naturaleza" },
    { word: "AMARILLO", clue: "Color del sol" },
    { word: "NEGRO", clue: "Color mas oscuro" },
    { word: "BLANCO", clue: "Color de la nieve" },
    { word: "GRIS", clue: "Color entre blanco y negro" },
    { word: "MARRON", clue: "Color de la tierra" },
    { word: "NARANJA", clue: "Color de la fruta citrica" },
    { word: "VIOLETA", clue: "Color entre azul y rojo" },
    { word: "ROSADO", clue: "Color claro y suave" },
    { word: "DORADO", clue: "Color del oro" },
    { word: "PLATEADO", clue: "Color de la plata" },
    { word: "CELESTE", clue: "Color azul claro" },
    { word: "BEIGE", clue: "Color marron claro" },
    { word: "TURQUESA", clue: "Color azul verdoso" },
    { word: "LILA", clue: "Color violeta claro" },
    { word: "MAGENTA", clue: "Color rosa intenso" },
    { word: "CIAN", clue: "Color azul brillante" },
    { word: "MARFIL", clue: "Color blanco hueso" },
    { word: "PLATA", clue: "Metal precioso de color gris brillante" },
    { word: "ORO", clue: "Metal precioso de color amarillo" },
  ],
  valores: [
    { word: "AMOR", clue: "Sentimiento de afecto profundo" },
    { word: "RESPETO", clue: "Consideracion hacia los demas" },
    { word: "HONESTIDAD", clue: "Cualidad de decir la verdad" },
    { word: "LEALTAD", clue: "Fidelidad hacia alguien o algo" },
    { word: "PERDON", clue: "Accion de disculpar a alguien" },
    { word: "GRATITUD", clue: "Sentimiento de agradecimiento" },
    { word: "HUMILDAD", clue: "Cualidad de ser modesto" },
    { word: "PACIENCIA", clue: "Capacidad de esperar con calma" },
    { word: "JUSTICIA", clue: "Dar a cada uno lo que le corresponde" },
    { word: "LIBERTAD", clue: "Capacidad de actuar por voluntad propia" },
    { word: "IGUALDAD", clue: "Trato sin discriminacion" },
    { word: "VERDAD", clue: "Conformidad con la realidad" },
    { word: "BONDAD", clue: "Cualidad de ser bueno" },
    { word: "VALENTIA", clue: "Cualidad de enfrentar el peligro" },
    { word: "CONFIANZA", clue: "Seguridad en alguien o algo" },
    { word: "ESPERANZA", clue: "Confianza en obtener algo deseado" },
    { word: "SINCERIDAD", clue: "Cualidad de expresarse sin mentira" },
    { word: "FORTALEZA", clue: "Capacidad de soportar la adversidad" },
    { word: "DIGNIDAD", clue: "Valor inherente de la persona" },
    { word: "HONOR", clue: "Cualidad moral que lleva al cumplimiento del deber" },
    { word: "COMPRENSION", clue: "Capacidad de entender a los demas" },
    { word: "DISCIPLINA", clue: "Capacidad de actuar ordenadamente" },
    { word: "COMPROMISO", clue: "Obligacion contraida" },
    { word: "GENEROSIDAD", clue: "Cualidad de dar sin esperar recibir" },
    { word: "COMPASION", clue: "Sentimiento de pena ante el sufrimiento ajeno" },
    { word: "CORTESIA", clue: "Demostracion de educacion y respeto" },
    { word: "AMABILIDAD", clue: "Cualidad de ser agradable con los demas" },
    { word: "ENTUSIASMO", clue: "Actitud de gran interes y animo" },
    { word: "OPTIMISMO", clue: "Actitud positiva ante la vida" },
    { word: "INTEGRIDAD", clue: "Cualidad de actuar con rectitud" },
  ],
  autos: [
    { word: "AUTO", clue: "Vehiculo de cuatro ruedas" },
    { word: "COCHE", clue: "Vehiculo para transportar personas" },
    { word: "CAMION", clue: "Vehiculo grande para carga" },
    { word: "MOTO", clue: "Vehiculo de dos ruedas" },
    { word: "BUS", clue: "Vehiculo de transporte publico" },
    { word: "TAXI", clue: "Vehiculo de alquiler con conductor" },
    { word: "MOTOR", clue: "Parte del vehiculo que genera movimiento" },
    { word: "RUEDA", clue: "Pieza circular que gira" },
    { word: "FRENO", clue: "Mecanismo para detener el vehiculo" },
    { word: "VOLANTE", clue: "Mando para dirigir el auto" },
    { word: "MARCHA", clue: "Velocidad del motor" },
    { word: "CARRETERA", clue: "Via para circular" },
    { word: "AUTOPISTA", clue: "Via rapida de varias pistas" },
    { word: "SEMAFORO", clue: "Senal luminosa de transito" },
    { word: "GARAJE", clue: "Lugar para estacionar" },
    { word: "TALLER", clue: "Lugar donde se reparan autos" },
    { word: "MECANICO", clue: "Persona que repara vehiculos" },
    { word: "GASOLINA", clue: "Combustible para autos" },
    { word: "BATERIA", clue: "Acumulador de energia del auto" },
    { word: "NEUMATICO", clue: "Cubierta de goma de la rueda" },
    { word: "LLANTA", clue: "Aro metalico de la rueda" },
    { word: "CONDUCTOR", clue: "Persona que maneja un vehiculo" },
    { word: "PILOTO", clue: "Conductor de un vehiculo de carreras" },
    { word: "TRAFICO", clue: "Circulacion de vehiculos" },
    { word: "ACCIDENTE", clue: "Suceso no deseado en la via" },
    { word: "LICENCIA", clue: "Permiso para conducir" },
    { word: "SEGURO", clue: "Proteccion contra danos" },
    { word: "FARO", clue: "Luz delantera del vehiculo" },
    { word: "CINTURON", clue: "Elemento de seguridad del auto" },
    { word: "BICICLETA", clue: "Vehiculo de dos ruedas a pedal" },
  ],
};
